# version: '3.9'

services:
  frontend:
    build: frontend
    ports:
      - "5173:5173"

  backend:
    build: backend
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./backend/src/create_tables.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
